name: FluxDash

runConfig:
  maxInstances: 1

services:
  app:
    image: node:20
    build_dir: .
    ports:
      - 3001:3000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://dash:dash@db:5432/dash?schema=public
      NODE_ENV: production
      TMDB_API_KEY: "${TMDB_API_KEY}"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dash
      POSTGRES_PASSWORD: dash
      POSTGRES_DB: dash
    volumes:
      - fluxdash-data:/var/lib/postgresql/data
