version: '3.8'
services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluxdash-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://dash:dash@postgres:5432/dash?schema=public
    command: >
      sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:16-alpine
    container_name: fluxdash-postgres
    restart: always
    environment:
      POSTGRES_USER: dash
      POSTGRES_PASSWORD: dash
      POSTGRES_DB: dash
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dash"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  pgdata:
    name: fluxdash-pgdata
  node_modules:
